openAI_key = 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
naver.api.client-id= Dh0Xjig9XaWYgbY28Syr
naver.api.client-secret= 1jnpOwpbHf