openAI_key = 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
naver.api.client-id = Dh0Xjig9XaWYgbY28Syr
naver.api.client-secret = 1jnpOwpbHf