openAI_key = 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
naver.api.client-id = Dh0Xjig9XaWYgbY28Syr
naver.api.client-secret = 1jnpOwpbHf